project:
  type: website
  title: "Geographic Information Systems Applications"
  resources:
    - "*/data/*"
    - environment.yml
    - "*/slides/*"
  output-dir: ./docs

lang: en

execute:
  freeze: false
  cache: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: assets/styles.css
    toc: true
    smooth-scroll: true
    highlight-style: atom-one
    bibliography: assets/references.bib

website:
  repo-url: https://github.com/sjsrey/g584s24/
  favicon: assets/favicon.png
  repo-actions: [issue]
  twitter-card: false
  page-navigation: true
  page-footer:
    center: "Course material by [Sergio Rey](https://sergerey.org). Available under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    collapse-level: 1
    logo: assets/logo.svg
    tools:
      - icon: github
        href: https://github.com/sjsrey/g584s24
    contents:
      - section: "Syllabus"
        contents:
          - syllabus.qmd
      - section: "Week 3: 1/30, 2/01"
        contents:
          - week-03/pandas.qmd
